### ISSUE TITLE
对于频繁需要修改的数据是否适合？

### ISSUE THREAD

**Issue by liuweiccy** [roowe/ets_cache#1]
看了你这个库的源码：有疑问向你请教。。。
1、对于频繁需要修改的数据是否适合存储？
2、在那些场景下适合用到该库？
3、在某个表不需要时，能不能删除它，并撤销进程？
4、在在清楚冷数据时会不会出现性能问题？(毕竟可以存储上百万的数据量)
5、对于没有timeout的ets,是否可以提供修改timeout的接口？
希望赐教！！

**Comment by roowe** [comment]
1、频繁修改，也就ets:insert的开销，这开销微秒级别的，个人认为可以使用
2、我们项目使用这个库原因是存储一些需要过期，同时允许脏数据（或者不会改动的，这样就不会有脏数据了），比如游戏里面，排行榜通过用户id查询他的nickname，英雄信息，以读为主，如果放ets_cache的话，第一次会从数据库加载，但是第二次以后的访问就会快很多，因为在ets里面。
3、某个表不需要的时候，可以清除所有对象就可以，空的ets并不会占用多少内存，实在有必要的话，也可以关闭，但是目前我不会有这个需求，也不打算去实现这个feature。
4、ets的select delete性能应该还可以，ets是单次遍历是微秒，100W也就1s左右，还是勉强够。但是如果有100W了，你应该考虑其他方案，这个玩意可能不太适合了。
5、ets本身就是一个存储引擎，timeout这个是业务领域，它不提供也再正常不过。
